server:
  port: 9004
spring:
  application:
    name: book-trade
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${book-trade.database.host}:3306/book-trade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${book-trade.database.password}
  cloud:
    alibaba:
      seata:
        tx-service-group: book-trade-group
  rabbitmq:
    listener:
      simple:
        auto-startup: false
autoconfigure:
    exclude: io.seata.spring.boot.autoconfigure.SeataAutoConfiguration

# Seata配置
seata:
  enabled: false
  application-id: ${spring.application.name}
  tx-service-group: book-trade-group



mybatis:
  # 添加这行来指定XML映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl