server:
  port: 9002
spring:
  application:
    name: user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${book-user.database.host}:3306/book-product?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${book-user.database.password}
knife4j:
  enable: true
  openapi:
    title: 书驿用户服务接口文档
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.booknook.user.controller
