server:
  port: 8080
spring:
  application:
    name: book-gateway
  cloud:
    gateway:
      routes:
        - id: product # 路由规则id，自定义，唯一
          uri: lb://book-product # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/products/**
            - Path=/search/** # 这里是以请求路径作为判断规则
        - id: user
          uri: lb://book-user
          predicates:
            - Path=/users/**
            - Path=/addresses/**
        - id: trade
          uri: lb://book-trade
          predicates:
            - Path=/orders/**
        - id: pay
          uri: lb://book-payment
          predicates:
            - Path=/pay-orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
